const $ = id => document.getElementById(id);
const DAY = 24 * 60 * 60 * 1000;
const state = {users:[],reservations:[],viewDate:null,selection:null,confirmSelection:null,cancelReservation:null};

function startOfDay(value){const date=new Date(value);date.setHours(0,0,0,0);return date}
function addDays(value,days){const date=new Date(value);date.setDate(date.getDate()+days);return startOfDay(date)}
function sameDay(a,b){return startOfDay(a).getTime()===startOfDay(b).getTime()}
function naturalDay(date){const diff=Math.round((startOfDay(date)-startOfDay(new Date()))/DAY);if(diff===0)return"Today";if(diff===1)return"Tomorrow";if(diff===-1)return"Yesterday";return new Intl.DateTimeFormat(undefined,{weekday:"long"}).format(date)}
function fullDate(date){return new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(date)}
function shortDate(date){return new Intl.DateTimeFormat(undefined,{month:"long",day:"numeric",year:"numeric"}).format(date)}
function time(date){return new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(date)}
function compactDay(date){return new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric"}).format(date)}
function durationLabel(minutes){const hours=Math.floor(minutes/60),remainder=minutes%60;return hours&&remainder?`${hours} hr ${remainder} min`:hours?`${hours} hr${hours===1?"":"s"}`:`${remainder} min`}
function reservationRange(start,end){return sameDay(start,end)?`${time(start)} — ${time(end)}`:`${time(start)} ${compactDay(start)} — ${time(end)} ${compactDay(end)}`}
function initialSelection(){const now=new Date(),start=new Date(now);start.setMinutes(now.getMinutes()+1,0,0);return{start,end:new Date(start.getTime()+60*60*1000)}}
function owner(reservation){return reservation.display_name||reservation.username||reservation.email}
function overlapReservation(start,end){return state.reservations.find(reservation=>start<new Date(reservation.end_time)&&end>new Date(reservation.start_time))}
function storageSelection(){return{workspaceGb:Number($("workspace-gb").value),tempStorageGb:Number($("temp-storage-gb").value)}}
function storageError(){const{workspaceGb,tempStorageGb}=storageSelection();if(!Number.isInteger(workspaceGb)||!Number.isInteger(tempStorageGb)||workspaceGb<1||tempStorageGb<1)return"Workspace and temporary storage must each be at least 1 GB.";if(workspaceGb+tempStorageGb>200)return"Workspace and temporary storage can total at most 200 GB.";return""}
function selectionError(){const{start,end}=state.selection;if(!$("target-email").validity.valid)return"Enter an approved user email.";const storage=storageError();if(storage)return storage;if(start<=new Date())return"This time has already passed.";if(end<=start)return"The reservation must end after it starts.";if(overlapReservation(start,end))return"Part of this session overlaps an unavailable time.";return""}
function notify(title,message,type="success"){$("notice-title").textContent=title;$("notice-message").textContent=message;$("admin-notice").className=`notice ${type}`}
async function request(path,options={}){const response=await fetch(path,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.detail||"Request failed");return data}

const emailCompletionRefreshers=[];
function attachEmailCompletion(input,values){const wrapper=document.createElement("span"),ghost=document.createElement("span");wrapper.className="inline-email-completion";ghost.className="inline-email-ghost";ghost.setAttribute("aria-hidden","true");input.parentNode.insertBefore(wrapper,input);wrapper.append(ghost,input);let suggestion="";function update(){const typed=input.value.trim().toLowerCase(),matches=[...new Set(values().filter(Boolean).map(value=>value.toLowerCase()))];suggestion=typed?matches.find(value=>value.startsWith(typed)&&value!==typed)||"":"";ghost.textContent=suggestion}input.addEventListener("input",update);input.addEventListener("focus",update);input.addEventListener("blur",()=>{ghost.textContent=""});input.addEventListener("keydown",event=>{if(event.key==="Tab"&&suggestion){input.value=suggestion;input.dispatchEvent(new Event("input",{bubbles:true}));suggestion="";ghost.textContent=""}});emailCompletionRefreshers.push(update)}
function refreshEmailCompletions(){emailCompletionRefreshers.forEach(refresh=>refresh())}

async function loadUsers(){state.users=await request("/admin/users");refreshEmailCompletions()}
async function loadReservations(){state.reservations=await request("/admin/reservations");refreshEmailCompletions();renderCalendar();renderReservationList()}

function renderDayStrip(){const strip=$("admin-day-strip");strip.replaceChildren();const today=startOfDay(new Date()),distance=Math.round((state.viewDate-today)/DAY),first=addDays(today,Math.floor(distance/7)*7);for(let index=0;index<7;index++){const date=addDays(first,index),button=document.createElement("button");button.type="button";button.className="day-chip";if(sameDay(date,state.viewDate))button.classList.add("active");if(sameDay(date,today))button.classList.add("today");button.setAttribute("aria-label",fullDate(date));const label=document.createElement("span"),number=document.createElement("strong");label.textContent=naturalDay(date);number.textContent=new Intl.DateTimeFormat(undefined,{day:"numeric"}).format(date);button.append(label,number);button.addEventListener("click",()=>changeDay(date));strip.append(button)}}
function renderTimeline(){const timeline=$("admin-timeline"),dayStart=startOfDay(state.viewDate),dayEnd=addDays(dayStart,1),now=new Date();timeline.replaceChildren();const grid=document.createElement("div");grid.className="timeline-grid";for(let index=0;index<96;index++){const cell=document.createElement("span");cell.className=`quarter-cell${(index+1)%4===0?" hour":""}`;grid.append(cell)}timeline.append(grid);const trackLabel=document.createElement("span");trackLabel.className="calendar-track-label";trackLabel.textContent="GPU availability";timeline.append(trackLabel);const labels=document.createElement("div");labels.className="hour-labels";for(let hour=0;hour<=24;hour++){const label=document.createElement("span");label.className=`hour-label${hour%2===0?" major":""}`;label.style.left=`${hour/24*100}%`;label.textContent=hour===0||hour===24?"12 AM":hour<12?`${hour} AM`:hour===12?"12 PM":`${hour-12} PM`;labels.append(label)}timeline.append(labels);
  function appendSpan(rawStart,rawEnd,className,description,click){if(rawStart>=dayEnd||rawEnd<=dayStart)return null;const start=new Date(Math.max(rawStart,dayStart)),end=new Date(Math.min(rawEnd,dayEnd)),block=document.createElement("div");block.className=className;block.style.left=`${(start-dayStart)/(dayEnd-dayStart)*100}%`;block.style.width=`${(end-start)/(dayEnd-dayStart)*100}%`;block.title=description;block.setAttribute("aria-label",description);if(click){block.tabIndex=0;block.classList.add("admin-cancellable");block.addEventListener("click",click);block.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();click()}})}timeline.append(block);return block}
  state.reservations.forEach(reservation=>{const start=new Date(reservation.start_time),end=new Date(reservation.end_time),description=`${owner(reservation)} · ${reservation.email}\n${reservationRange(start,end)}\nClick to cancel`;appendSpan(start,end,"availability-block",description,()=>openCancel(reservation))});
  if(sameDay(dayStart,now)){const minutes=now.getHours()*60+now.getMinutes(),past=document.createElement("div"),marker=document.createElement("div");past.className="past-block";past.style.width=`${minutes/1440*100}%`;marker.className="now-marker";marker.style.left=past.style.width;timeline.append(past,marker)}
  const conflict=selectionError(),description=`Selected for ${$("target-email").value}: ${reservationRange(state.selection.start,state.selection.end)} · ${durationLabel((state.selection.end-state.selection.start)/60000)}`,selection=appendSpan(state.selection.start,state.selection.end,`selection-block${conflict?" conflict":""}`,description);if(selection)requestAnimationFrame(()=>{const scroller=$("admin-timeline-scroller"),target=selection.offsetLeft+selection.offsetWidth/2-scroller.clientWidth/2;scroller.scrollTo({left:Math.max(0,target),behavior:"smooth"})})}
function renderCalendar(){$("admin-day-context").textContent=naturalDay(state.viewDate);$("admin-calendar-date").textContent=fullDate(state.viewDate);$("admin-return-today").classList.toggle("hidden",sameDay(state.viewDate,new Date()));renderDayStrip();renderTimeline()}
function renderReservationList(){const query=$("reservation-search").value.trim().toLowerCase(),reservations=state.reservations.filter(reservation=>`${reservation.email} ${reservation.display_name||""} ${reservation.username||""}`.toLowerCase().includes(query)),list=$("admin-reservation-list");list.replaceChildren();if(!reservations.length){const empty=document.createElement("div");empty.className="admin-empty";empty.textContent=query?"No reservations match that email or name.":"No current or upcoming reservations.";list.append(empty);return}reservations.forEach(reservation=>{const row=document.createElement("article");row.className="admin-reservation";row.title=`${owner(reservation)} · ${reservation.email}`;const identity=document.createElement("div"),name=document.createElement("strong"),email=document.createElement("small");name.textContent=owner(reservation);email.textContent=reservation.email;identity.append(name,email);const timing=document.createElement("div"),range=document.createElement("time"),storage=document.createElement("small");range.textContent=`${formatDateTime(reservation.start_time)} — ${formatDateTime(reservation.end_time)}`;storage.textContent=`${reservation.workspace_gb} GB workspace · ${reservation.temp_storage_gb} GB temporary`;timing.append(range,storage);if(reservation.duration_override){const badge=document.createElement("span");badge.className="extended-badge";badge.textContent="Extended duration";timing.append(badge)}const cancel=document.createElement("button");cancel.type="button";cancel.className="button danger";cancel.textContent="Cancel";cancel.addEventListener("click",()=>openCancel(reservation));row.append(identity,timing,cancel);list.append(row)})}
function formatDateTime(value){return new Intl.DateTimeFormat(undefined,{weekday:"short",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value))}

function setStartTimeControls(date){const hour=date.getHours();$("admin-start-time-text").value=`${String(hour%12||12).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`;["admin-period-am","admin-period-pm"].forEach(id=>$(id).classList.toggle("active",id===(hour>=12?"admin-period-pm":"admin-period-am")))}
function applyTypedTime(){const match=$("admin-start-time-text").value.trim().match(/^(\d{1,2}):([0-5]\d)$/);if(!match||Number(match[1])<1||Number(match[1])>12)return false;let hour=Number(match[1])%12;if($("admin-period-pm").classList.contains("active"))hour+=12;const duration=state.selection.end-state.selection.start,start=new Date(state.viewDate);start.setHours(hour,Number(match[2]),0,0);state.selection={start,end:new Date(start.getTime()+duration)};updateSelection();return true}
function updateSelection(){const{start,end}=state.selection,minutes=Math.round((end-start)/60000),error=selectionError(),{workspaceGb,tempStorageGb}=storageSelection(),total=workspaceGb+tempStorageGb;state.viewDate=startOfDay(start);setStartTimeControls(start);$("storage-total").textContent=`${Number.isFinite(total)?total:"—"} / 200 GB`;$("storage-total-box").classList.toggle("invalid",Boolean(storageError()));$("admin-duration-value").textContent=durationLabel(minutes);$("admin-composer-date").textContent=sameDay(start,end)?`${naturalDay(start)} · ${shortDate(start)}`:`Crosses midnight · ${compactDay(start)} → ${compactDay(end)}`;$("admin-composer-range").textContent=reservationRange(start,end);$("admin-composer-status").textContent=error||"Available to reserve";$("admin-composer-summary").classList.toggle("conflict",Boolean(error));$("admin-selection-error").textContent=error;$("admin-selection-error").classList.toggle("hidden",!error);$("admin-confirm-booking").disabled=Boolean(error);$("admin-duration-down").disabled=minutes<=15;$("admin-duration-up").disabled=false;renderCalendar()}
function changeDuration(delta){const current=(state.selection.end-state.selection.start)/60000,next=Math.max(15,current+delta);state.selection.end=new Date(state.selection.start.getTime()+next*60000);updateSelection()}
function changeDay(date){const duration=state.selection.end-state.selection.start,start=new Date(date);start.setHours(state.selection.start.getHours(),state.selection.start.getMinutes(),0,0);state.selection={start,end:new Date(start.getTime()+duration)};updateSelection();document.querySelector(".schedule").scrollIntoView({behavior:"smooth",block:"start"})}

function openCancel(reservation){state.cancelReservation=reservation;$("admin-cancel-copy").textContent=`Cancel ${owner(reservation)}’s reservation (${reservation.email}) from ${formatDateTime(reservation.start_time)} to ${formatDateTime(reservation.end_time)}?`;$("admin-cancel-dialog").showModal()}
async function confirmCancel(){const reservation=state.cancelReservation,button=$("admin-confirm-cancel");if(!reservation)return;button.disabled=true;button.textContent="Cancelling…";try{await request(`/admin/reservations/${reservation.id}`,{method:"DELETE"});$("admin-cancel-dialog").close();notify("Reservation cancelled",`The booking for ${reservation.email} was cancelled.`);await loadReservations()}catch(error){notify("Cancellation failed",error.message,"error")}finally{button.disabled=false;button.textContent="Cancel reservation"}}

$("admin-start-time-text").addEventListener("input",event=>{event.target.value=event.target.value.replace(/[^0-9:]/g,"").slice(0,5);if(/^\d{1,2}:[0-5]\d$/.test(event.target.value))applyTypedTime()});$("admin-start-time-text").addEventListener("blur",()=>{if(!applyTypedTime())setStartTimeControls(state.selection.start)});$("admin-start-time-text").addEventListener("keydown",event=>{if(event.key==="ArrowUp"||event.key==="ArrowDown"){event.preventDefault();const duration=state.selection.end-state.selection.start;state.selection.start=new Date(state.selection.start.getTime()+(event.key==="ArrowUp"?60000:-60000));state.selection.end=new Date(state.selection.start.getTime()+duration);updateSelection()}});["admin-period-am","admin-period-pm"].forEach(id=>$(id).addEventListener("click",()=>{["admin-period-am","admin-period-pm"].forEach(other=>$(other).classList.toggle("active",other===id));applyTypedTime()}));
$("admin-duration-down").addEventListener("click",()=>changeDuration(-15));$("admin-duration-up").addEventListener("click",()=>changeDuration(15));[$("target-email"),$("workspace-gb"),$("temp-storage-gb")].forEach(input=>input.addEventListener("input",updateSelection));
$("admin-previous-day").addEventListener("click",()=>changeDay(addDays(state.viewDate,-7)));$("admin-next-day").addEventListener("click",()=>changeDay(addDays(state.viewDate,7)));$("admin-return-today").addEventListener("click",()=>changeDay(new Date()));
$("admin-confirm-booking").addEventListener("click",()=>{const error=selectionError();if(error){notify("Check the reservation",error,"error");return}const storage=storageSelection();state.confirmSelection={start:new Date(state.selection.start),end:new Date(state.selection.end),email:$("target-email").value,...storage};$("admin-confirm-user").textContent=state.confirmSelection.email;$("admin-confirm-date").textContent=sameDay(state.confirmSelection.start,state.confirmSelection.end)?fullDate(state.confirmSelection.start):`${fullDate(state.confirmSelection.start)} → ${fullDate(state.confirmSelection.end)}`;$("admin-confirm-time").textContent=`${reservationRange(state.confirmSelection.start,state.confirmSelection.end)} · ${durationLabel((state.confirmSelection.end-state.confirmSelection.start)/60000)}`;$("admin-confirm-storage").textContent=`${storage.workspaceGb} GB workspace · ${storage.tempStorageGb} GB temporary`;$("admin-confirm-dialog").showModal()});
$("admin-edit-booking").addEventListener("click",()=>$("admin-confirm-dialog").close());$("admin-submit-booking").addEventListener("click",async()=>{const button=$("admin-submit-booking"),selection=state.confirmSelection;if(!selection)return;button.disabled=true;button.textContent="Reserving…";try{const allowExtended=selection.end-selection.start>3*60*60*1000;await request("/admin/reservations",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({email:selection.email,start_time:selection.start.toISOString(),end_time:selection.end.toISOString(),allow_extended:allowExtended,workspace_gb:selection.workspaceGb,temp_storage_gb:selection.tempStorageGb})});$("admin-confirm-dialog").close();notify("Reservation created",`Booked GPU time for ${selection.email}.`);await loadReservations()}catch(error){$("admin-confirm-dialog").close();notify("Reservation not created",error.message,"error")}finally{button.disabled=false;button.textContent="Confirm reservation"}});
$("admin-keep-reservation").addEventListener("click",()=>$("admin-cancel-dialog").close());$("admin-confirm-cancel").addEventListener("click",confirmCancel);$("reservation-search").addEventListener("input",renderReservationList);
$("whitelist-form").addEventListener("submit",async event=>{event.preventDefault();const button=$("whitelist-submit"),email=$("whitelist-email").value.trim();button.disabled=true;button.textContent="Allowlisting…";try{await request("/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,display_name:$("whitelist-name").value.trim()||null})});notify("User allowlisted",`${email} can now sign in and reserve GPU time.`);event.target.reset();await loadUsers();$("target-email").value=email;updateSelection()}catch(error){notify("User not allowlisted",error.message,"error")}finally{button.disabled=false;button.textContent="Allowlist user"}});
$("refresh-admin").addEventListener("click",()=>loadReservations().catch(error=>notify("Refresh failed",error.message,"error")));$("dismiss-notice").addEventListener("click",()=>$("admin-notice").classList.add("hidden"));$("logout").addEventListener("click",async()=>{await fetch("/auth/logout",{method:"POST"});location.href="/"});

attachEmailCompletion($("target-email"),()=>state.users.filter(user=>user.enabled).map(user=>user.email));
attachEmailCompletion($("reservation-search"),()=>state.reservations.map(reservation=>reservation.email));

(async()=>{state.selection=initialSelection();state.viewDate=startOfDay(state.selection.start);try{const me=await request("/me");if(!me.is_admin)throw new Error("This account is not an administrator.");$("admin-email").textContent=me.email;$("admin-name").textContent=me.display_name||me.username||"Cynaptics OpenGPU Admin";await Promise.all([loadUsers(),loadReservations()]);updateSelection();$("admin-topbar").classList.remove("hidden");$("admin-workspace").classList.remove("hidden");setInterval(()=>{if(!document.hidden)renderTimeline()},30000)}catch(error){$("denied-message").textContent=error.message;$("admin-denied").classList.remove("hidden")}})();
