BEGIN;

DROP TABLE IF EXISTS share_claims;

ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_identity_check;
ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_handle_key;
ALTER TABLE teams DROP COLUMN IF EXISTS handle;
ALTER TABLE teams ALTER COLUMN email SET NOT NULL;

COMMIT;
